# Generated by Django 5.2.7 on 2026-02-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParliamentaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[("Motion", "Motion")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(max_length=10, unique=True)),
                (
                    "participation_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Participation rate in parliamentary votes as a percentage.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Party",
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="PartyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("For", "For"),
                            ("Against", "Against"),
                            ("Abstain", "Abstain"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "parliamentary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraper.parliamentaryitem",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraper.party",
                    ),
                ),
            ],
            options={
                "unique_together": {("party", "parliamentary_item")},
            },
        ),
    ]
