# Generated by Django 5.2.7 on 2025-12-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partyvote",
            unique_together={("party", "parliamentary_item")},
        ),
    ]
