# Generated by Django 5.2.7 on 2026-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parliamentaryitem",
            name="text",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
