# Generated by Django 5.2.7 on 2026-01-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_partyvote_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"verbose_name": "Party", "verbose_name_plural": "Parties"},
        ),
    ]
