# Generated by Django 5.2.7 on 2026-02-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCAAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "PCA Analysis",
                "verbose_name_plural": "PCA Analyses",
            },
        ),
        migrations.CreateModel(
            name="PCAComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("explained_variance", models.FloatField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="analyzer.pcaanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Component",
                "verbose_name_plural": "PCA Components",
                "unique_together": {("analysis", "number")},
            },
        ),
        migrations.CreateModel(
            name="PCAComponentPartyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_scores",
                        to="analyzer.pcacomponent",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_scores",
                        to="scraper.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Component Party Score",
                "verbose_name_plural": "PCA Component Party Scores",
                "unique_together": {("component", "party")},
            },
        ),
        migrations.CreateModel(
            name="PCAItemLoading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loading", models.FloatField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_loadings",
                        to="analyzer.pcacomponent",
                    ),
                ),
                (
                    "parliamentary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_loadings",
                        to="scraper.parliamentaryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Item Loading",
                "verbose_name_plural": "PCA Item Loadings",
                "unique_together": {("component", "parliamentary_item")},
            },
        ),
    ]
