# Generated by Django 5.2.7 on 2026-01-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pcaanalysis",
            options={
                "verbose_name": "PCA Analysis",
                "verbose_name_plural": "PCA Analyses",
            },
        ),
    ]
